filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/log/nginx/access.log

output.elasticsearch:
  hosts: ["ELASTIC:9200"]
  indices:
    - index: "Filebeat-ng-logs-%{+yyyy.MM.dd}"

setup.template.name: "nginx-logs-filebeatp"
setup.template.pattern: "nginx-logs-*"
setup.ilm.enabled: false